### ISSUE TITLE
Running Pydot code and recieved and error saying "GraphViz's Executables not found"; using python 2.7.3 and windows 8.1

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erocarrera/pydot#102]
```
What steps will reproduce the problem?
1. install graphviz and pydot
2. set up code for a graph
3. run graph.write_png

What is the expected output? What do you see instead?
The expected output is suppose to be a graph, what I see is 

Traceback (most recent call last):
  File "<pyshell#12>", line 1, in <module>
    graph.write_png('example1_graph.png')
  File "C:\Python27\lib\site-packages\pydot.py", line 1602, in <lambda>
    lambda path, f=frmt, prog=self.prog : self.write(path, format=f, prog=prog))
  File "C:\Python27\lib\site-packages\pydot.py", line 1696, in write
    dot_fd.write(self.create(prog, format))
  File "C:\Python27\lib\site-packages\pydot.py", line 1727, in create
    'GraphViz\'s executables not found' )
InvocationException: GraphViz's executables not found


What version of the product are you using? On what operating system?

OS: Windows 8.1
Graphviz: 0.4.3
Pydot: 1.0.2
Python: 2.7.9

Please provide any additional information below.

Tried the uninstall and reinstall with different patterns routine, changed the 
paths, and downloaded different versions of each; nothing worked. 

```

Original issue reported on code.google.com by `AlexJame...@gmail.com` on 10 Apr 2015 at 3:52

**Comment by johnyf** [comment]
Same with #109. Please add GraphViz to the path.
