### ISSUE TITLE
Can't pip install latest pydot

### ISSUE THREAD

**Issue by mrjbq7** [erocarrera/pydot#144]
Trying to install pydot 1.2.3 gives me this error:

```python
$ pip install -U pydot
Collecting pydot
Requirement already up-to-date: pyparsing>=2.1.4 in /usr/local/lib/python2.7/site-packages (from pydot)
Installing collected packages: pydot
  Found existing installation: pydot 1.2.2
    Uninstalling pydot-1.2.2:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/LICENSE'
```

**Comment by johnyf** [comment]
No problems here. This seems unrelated to `pydot`. Write permission needs to be used for `/usr/local/...`, for example via `sudo`. It would be better to install Python under `$HOME` (e.g., by cloning [`cpython`](https://github.com/python/cpython) and building from source), and even better to use a `virtualenv` on top.

**Comment by mrjbq7** [comment]
This is with vanilla homebrew on Mac OSX. Why in the world is it writing a LICENSE file to /usr/local?

**Comment by mrjbq7** [comment]
I'm sorry, for some reason I had a ``/usr/local/LICENSE`` that seems to have gotten in the way and I didn't notice.

```
$ sudo rm /usr/local/LICENSZE

$ pip install -U pydot
Collecting pydot
Requirement already up-to-date: pyparsing>=2.1.4 in /usr/local/lib/python2.7/site-packages (from pydot)
Installing collected packages: pydot
  Found existing installation: pydot 1.2.2
    Uninstalling pydot-1.2.2:
      Successfully uninstalled pydot-1.2.2
Successfully installed pydot-1.2.3
```

**Comment by johnyf** [comment]
There isn't any way I can imagine of `pydot` writing any `LICENSE` file there on its own. When installed, `pydot` is under `site-packages`. Perhaps the `LICENSE` file was temporarily created by `pip` while building the package, or some `sudo` process that had been interrupted.
