### ISSUE TITLE
node, edge, graph, cluster do not create getters/setters for custom attributes

### ISSUE THREAD

**Issue by ainterr** [erocarrera/pydot#151]
The Node, Edge, Graph, and Cluster classes are generic enough to handle attributes other than the defaults (https://github.com/erocarrera/pydot/blob/master/pydot.py#L81-L89) but getters/setters are only created for defaults (https://github.com/erocarrera/pydot/blob/master/pydot.py#L572). If I pass a custom attribute to one of these classes I should be able to access it like:

```bash
>>> import pydot
>>> e = pydot.Edge(0, 1, minlen=1, foo='bar')
>>> e.get_minlen()
1
>>> e.get_bar()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Edge' object has no attribute 'get_bar'
```

Instead, I have to do the rather unintuitive:

```bash
>>> e.obj_dict['attributes']['foo']
'bar'
```

**Comment by johnyf** [comment]
Instead of getters and setters, [properties](https://docs.python.org/3.7/library/functions.html#property) are recommended in Python. Dynamically creating methods is implicit, nested, and complex ([PEP 20](https://www.python.org/dev/peps/pep-0020/)). Explicit is better, so `e.minlen = 1` would probably be easier to keep track of.

`pydot` is an interface to GraphViz. For working with graphs within Python, I would recommend using [`networkx`](https://github.com/networkx/networkx/), which interfaces to GraphViz via `pydot`.

**Comment by peternowee** [comment]
@ainterr: Thanks for reporting. 

Still reproducible with current master (pydot 1.4.2.dev0+682edb7b) on Python 3.7.3:

```python3
>>> e = pydot.Edge(0, 1, minlen=1, foo='bar')
>>> e.get_minlen()
1
>>> e.get_foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Edge' object has no attribute 'get_foo'
```

One way to get to the value of a custom DOT attribute for which no convenience method is available is to use the generic getter/setter methods (`Common.get()`, `Common.set()`, which are inherited as `Node.get()`, `Node.set()`, `Edge.get()`, etc.):

```python3
>>> e.get('foo')
'bar'
```

Another way is to request additional convenience methods to be generated for your custom DOT attributes (pydot 1.4.1 or 1.4.2.dev0):

```python3
>>> e.create_attribute_methods({'foo'})
>>> e.get_foo()
'bar'
```

I understand you actually want this to happen on the fly at the moment the instance is created, which is an interesting idea and might have been possible (by letting the `__init__()` methods extend the set of attributes to call `create_attribute_methods()` with).

However, some changes are planned in PR pydot/pydot#242 that will make this impossible again. If that PR gets merged, getter/setter methods will be bound to the class instead of the instance. This happens during `import pydot` already. From then on, you would need to create your own subclass and add the `@create_attribute_methods()` decorator to that.

For example (with current PR pydot/pydot#242, commit 9cb6e0d0, targeted for pydot 2.0.0, but undecided yet, so still very much subject to change!):

```python3
>>> import pydot
>>> @pydot.create_attribute_methods({'foo'})
... class CustomEdge(pydot.Edge):
...     pass
... 
>>> e = CustomEdge(0, 1, minlen=1, foo='bar')
>>> e.get_minlen()
1
>>> e.get_foo()
'bar'
```

This of course assumes that at the time you create the class you know which custom DOT attributes you will be using. If that set can change afterwards, it would become more difficult and you would have to dynamically subclass or something, I don't know.

Also note that I have not tested subclassing much myself yet. I do not know for example if pydot always correctly recognizes subclasses of its own classes. Please report any bugs that you might meet.

Btw, the links in your original post referencing line numbers in the `master` branch are outdated. These are the correct, permanent links:
- `https://github.com/pydot/pydot/blob/ae80697e61e9e3b265175676bb78db6396542616/pydot.py#L81-L89`
- `https://github.com/pydot/pydot/blob/ae80697e61e9e3b265175676bb78db6396542616/pydot.py#L572`

I will leave this issue open for more/better ideas on getters/setters for custom DOT attributes. If you can, please consider the proposed changes in pydot/pydot#242 and pydot/pydot#250 then as well.

@johnyf I opened a new issue pydot/pydot#250 for Python properties.
