### ISSUE TITLE
Pydot does not escape node ends with ":,"

### ISSUE THREAD

**Issue by PandaDrunkard** [erocarrera/pydot#178]
pydot              1.2.4

It seems that pydot does not escape node ends with ":," (colon + comma) and causes following exception.

```
'dot', '-Tpng', '/var/folders/j1/w_zh6pj55k36yt8f6_bjh94r0000gn/T/tmp_3otqp04'] return code: 1

stdout, stderr:
 b''
b"Error: /var/folders/j1/w_zh6pj55k36yt8f6_bjh94r0000gn/T/tmp_3otqp04: syntax error in line 8 near ','\n"

Traceback (most recent call last):
  File "my.py", line 22, in <module>
    draw_corenlp_dependencies(deps, 'my.png')
  File "../common/drawers.py", line 15, in draw_corenlp_dependencies
    graph.write_png(file_name)
  File "aaa/site-packages/pydot.py", line 1673, in new_method
    encoding=encoding)
  File "aaa/site-packages/pydot.py", line 1756, in write
    s = self.create(prog, format, encoding=encoding)
  File "aaa/site-packages/pydot.py", line 1884, in create
    assert p.returncode == 0, p.returncode
AssertionError: 1
```

I haven't tried other combinations, but the node ends with ":." (colon + period) is appropriately escaped as shown in my example.

Here is my python code.
```
def draw_corenlp_dependencies(deps, file_name='graph.png'):
    graph = pydot.Dot(graph_type='graph')
    for d in deps:
        edge = pydot.Edge(d.governor, d.dependent)
        graph.add_edge(edge)
    graph.write(file_name + '.dot')
```

It outputs the following. ":," is not escaped, but ":." is escaped.
```
graph G {
0:ROOT -- 18:field;
3:processing -- 1:Natural;
3:processing -- 2:language;
18:field -- 3:processing;
5:Wikipedia -- 4:From;
3:processing -- 5:Wikipedia;
5:Wikipedia -- 6:,;
12:processing -- 7:the;
12:processing -- 8:free;
12:processing -- 9:encyclopedia;
12:processing -- 10:Natural;
12:processing -- 11:language;
5:Wikipedia -- 12:processing;
14:NLP -- "13:-LRB-";
12:processing -- 14:NLP;
14:NLP -- "15:-RRB-";
18:field -- 16:is;
18:field -- 17:a;
21:science -- 19:of;
21:science -- 20:computer;
18:field -- 21:science;
21:science -- 22:,;
24:intelligence -- 23:artificial;
21:science -- 24:intelligence;
21:science -- 25:,;
21:science -- 26:and;
21:science -- 27:linguistics;
27:linguistics -- 28:concerned;
31:interactions -- 29:with;
31:interactions -- 30:the;
28:concerned -- 31:interactions;
33:computers -- 32:between;
31:interactions -- 33:computers;
33:computers -- 34:and;
39:languages -- 35:human;
37:natural -- "36:-LRB-";
35:human -- 37:natural;
37:natural -- "38:-RRB-";
33:computers -- 39:languages;
18:field -- "40:.";
}
```

**Comment by peternowee** [comment]
Stepping through the code, I found there are two reasons why this is going wrong:

- The first problem is that pydot thinks that you are using ports, because of the colon (`:`). The node name (e.g. `6:,`) first matches with `id_re_with_port`. @PandaDrunkard: I assume you did not mean to use DOT-ports here, right? In other words, you wanted `6:,` to be the entire name (ID in DOT terms) of the node, right? You did not mean `6` to be the ID and `,` to be a DOT port, right? I hope you understand what I mean to ask. See the [DOT Language definition](https://www.graphviz.org/doc/info/lang.html) and the [description of the portPos type](https://www.graphviz.org/doc/info/attrs.html#k:portPos). Anyway, the issue of ambiguity of colons and ports in node names is covered in pydot/pydot#118 and I hope to solve that in pydot 2.0.0/1.5.0.

- The second problem occurs when pydot arrives at the right-hand side of the name (`,`), namely that the current regular expression (regex) for `id_re_num` allows commas in numeric IDs, whereas according to the [DOT Language definition](https://www.graphviz.org/doc/info/lang.html) commas are not allowed in there at all and the ID should be quoted.

Since the first problem is discussed in issue pydot/pydot#118 already, I hope we use this issue (pydot/pydot#178) for the second problem, the mistakes currently (pydot 1.4.1) in the `id_re_num` regex. There are other problems with the pydot regex as well, such as with the minus sign (`-`) and the allowing of multiple decimal points, and I hope we can consider those part of this issue 178 as well.

I think this issue needs to be solved by changing the pydot regex for numeric IDs to fully reflect the one in the [DOT Language definition](https://www.graphviz.org/doc/info/lang.html). This was done earlier in fork pydot-ng https://github.com/pydot/pydot-ng/commit/64e3a636df2b5d94ce8ab0a1cbb5baa6cd4594ae and was in there from 2015 until 2018:

```regex
^[-]?(\.[0-9]+|[0-9]+(\.[0-9]*)?)$
```

For some reason, pydot-ng reverted it again just before the whole fork got archived in 2018 (https://github.com/pydot/pydot-ng/commit/c985db99323d7c9f6f223ff2321b130b54261090), but @prmtl told me he does not remember why. Perhaps it was to prepare for a merge between pydot and pydot-ng and ensure compatibility between the two. Whatever the reason, I still think the pydot-ng version was the most correct. The DOT Language definition already gives a pseudo-regex and I myself even arrived at exactly the same regex before finding out pydot-ng had it earlier already. I think everyone would arrive at the same regex given the DOT Language definition. I also checked many different strings with this regex and compared them with actual Graphviz behavior and the results were consistent (I think it was Graphviz 2.38.0, maybe 2.40.1).

I plan improve the quoting and regexes, including the one discussed here, in pydot 2.0.0/1.5.0. Not in pydot 1.4.x, because these will be breaking changes for some users, even if it is only about better DOT syntax adherence.

By the way, the change may lead to questions about the peculiarities of what the DOT Language considers numerals, like why it only allows a period (`.`) as a decimal point, why the comma (`,`) cannot be used (not even as a thousands separator) or why values like `.1`, `-.1`, `1.` and `-1.` are considered numerals, etc. Let me just say already that I think such questions should be raised with the authors of the DOT Language (graphviz.org), not pydot, that it is up to them to decide about that, and that until they change it, pydot should just follow the definition as it is.

###### Versions: python 3.7.3, pydot 1.4.1

**Comment by pktpls** [comment]
Have had the same problem with version numbers in node properties, which end up as e.g. `ipkVersion=1.4.0`, while they should actually be wrapped in quotes

**Comment by ferdnyc** [comment]
(Or I suppose we could just convert it to a number, then back to a string, and see if it comes out the same. That might actually be safer.)

```python
def is_numeric(attr: str) -> bool:
    try:
        return str(float(attr)) == attr
    except ValueError:
        return False
```

**Comment by ferdnyc** [comment]
#439 will fix that, but I forgot to mention that in the meantime, one way you can work around it is by double-quoting values like `1.4.0` yourself. For example:

```python
>>> import pydot
>>> n = pydot.Node("n", ipkVersion="1.4.0")
>>> n.to_string()  # Problem
'n [ipkVersion=1.4.0];'
>>> n2 = pydot.Node("n2", ipkVersion='"1.4.0"')
>>> n2.to_string()  # 👍🏽
'n2 [ipkVersion="1.4.0"];'
```
