### ISSUE TITLE
quote_if_necessary is not bulletproof

### ISSUE THREAD

**Issue by Lucas-C** [erocarrera/pydot#187]
Bug reproduction:
```
import pydot
g = pydot.Dot(root='"";""')
print(g.to_string())
g.write_png('out.png', prog='twopi')
```
Output:
```
digraph G {
root="";"";
}

['twopi', '-Tpng', '/tmp/tmp8wygs5cn'] return code: -11

stdout, stderr:
 b''
b''

Traceback (most recent call last):
  File "repro.py", line 4, in <module>
    g.write_png('out.png', prog='twopi')
  File ".../lib/python3.6/site-packages/pydot.py", line 1673, in new_method
    encoding=encoding)
  File ".../lib/python3.6/site-packages/pydot.py", line 1756, in write
    s = self.create(prog, format, encoding=encoding)
  File ".../lib/python3.6/site-packages/pydot.py", line 1884, in create
    assert p.returncode == 0, p.returncode
AssertionError: -11
```

That's because `quote_if_necessary('"";""')` returns `False` whereas some escaping needs to be done

**Comment by ankostis** [comment]
It even fails `pydot.quote_if_necessary("a,b")` which is left unquoted.
We need a new goithub-label to mark all bugs with quoting,
and rewrite the `needs_quotes()`.

**Comment by PaulSzymanski** [comment]
This bit me as well. Strings containing a colon (`:`) are not quoted but should be.

**Comment by stevenjswanson** [comment]
I'll pile on as well.  The string `'\\"'` causes `to_string()` to generate invalid output.

```
import pydot

g = pydot.Dot()
g.add_node(pydot.Node("b", label='\\"'))
g2 = pydot.graph_from_dot_data(g.to_string())
assert g2 is not None, "Graph did not parse."
```

**Comment by lkk7** [comment]
@stevenjswanson thanks for refreshing this issue! PyDot has been in a dead state for some time, but it was recently revived.
I'll look into this issue in free time.

**Comment by ferdnyc** [comment]
I believe the situation is much improved in pydot 3.0.1, partly by the splitting of  ID and attribute quoting, but it seems there are still some improvements that could be made around escaping.

In graphviz, if you want quotation marks in a label you can either escape them, or use an HTML-like string. Either of these will correctly label a node `";"`:

```gv
node1 [label="\";\""];
node2 [label=<";">];
```

Unfortunately the escaping rules in pydot are still unchanged from previous versions, and they can be a little weird. They only trigger if a string _doesn't_ start and end with `"` or `<`/`>`. But when they trigger...

* `label='\";\"'` becomes `label=";"` in the output, same as `label='";"'`. That's probably consistent with Python string handling.
* `label=r'\";\"'` (note the raw string there) or `label='\\";\\"'` _OR_ `label='\\\";\\\"'` all become `label="\\\\";\\\\""` in the output, which seems completely messed up. It's effectively _escaping the backslashes_ to make them present in the output, rather than using them as escape characters. But it's doing it... weird. 
* Oh, and just for fun `label='\\\\";\\\\"'` becomes `label="\\\\\\";\\\\\\""`. It's somehow going from 4 to 6 there, which is wrong no matter how you interpret it.

Part of the rule should be, I think, "if you do your own quoting then you have to do your own escaping". (Meaning, the OP's `'"";""'` I don't really feel is valid, because how can pydot know the intent there? Is it meant to be `"\";\""`? `\"\";\"\"`?)

And that part of the logic seems to mostly work — if you pass pydot the string `'"\\";\\""'` (or `r'"\";\""'`) as a label or node name, it will become `"\\";\\""` which is correct. Similarly, `pydot.Node("n", label='<";">')` will be `n [label=<";">];` in the `to_string()` output.

But when pydot's escaping logic does kick in, things get kind of insane, still.

**Comment by Lucas-C** [comment]
Thank you all for your feedbacks.

I agree with your analysis @ferdnyc 

Still, don't you think that `pydot.quote_attr_if_necessary('"";""')` should produce a warning or raise an error?

**Comment by ferdnyc** [comment]
@Lucas-C 
> Still, don't you think that `pydot.quote_attr_if_necessary('"";""')` should produce a warning or raise an error?

Hmm. That's a good question.

Itself, _directly_... I don't think I do. Primarily because it's only ever called implicitly, and (now) only during output. Which is too late to decide that you've set a wrong value, IMHO.

If we're going to validate the values set for attributes or names, I think we need to do that when they're **set**, not when they're consumed. (Like how the constructors used to call `quote_if_necessary()` on the values passed in to them — but still it never warned or raised an exception. It just silently applied corrections to the value before it was stored, which turned out to be more annoying than helpful. See #180.)

I still don't think we'd be able to catch **all** bad values without actually _parsing_ them — which [we don't do and **really** don't _want_ to do](https://github.com/pydot/pydot/issues/366#issuecomment-2175624023). Most likely we can't even catch _most_ bad values.

So I'm not sure I'm willing to commit to making the quoting, as you say, "bulletproof", because ultimately we're passing these values to another program — `dot`, or whatever graphviz tool the user selects to process their graph definitions — and that tool is the final authority on valid syntax, not pydot. The more we meddle with the values the user supplies, the more likely we are to do more harm than good — like with the current auto-escaping.

Still, that being said, there are probably **certain** things we can detect, like unescaped quotes inside a quoted string. And rejecting those or at least warning the user about them — when they're _set_, rather than when generating output — wouldn't be a bad idea. But the moment our validation checks have any possibility of false positive errors, because they reject some string that, Oh! turns out, actually _is_ valid in graphviz... that's the moment we're back to doing more harm than good.

**Comment by lkk7** [comment]
The logging is already set up, so it could be used for warnings.

If it'd be **on** by default, the checking has to be really "narrow" and only scan for 100% certain errors. Don't want to annoy users with unwanted logs. 

If it's opt-in, then probably no one would know about it because the user base is very stabilized and probably doesn't check updates unless something breaks.

A very minor thing to consider is performance, I've seen people complain about speed when creating insanely big graphs programmatically with pydot. That needs a separate issue, but I hope that kind of scan on every node creation wouldn't make this worse.

**Comment by ferdnyc** [comment]
> A very minor thing to consider is performance, I've seen people complain about speed when creating insanely big graphs programmatically with pydot. That needs a separate issue, but I hope that kind of scan on every node creation wouldn't make this worse.

That's a good point, we should probably at least give `dot_parser` a way to bypass those checks, since we can assume that all of its values are going to be legal graphviz syntax. A constructor argument `_validate=False` or whatever should suffice. (And it doesn't ever use the `.set*()` methods, so there's no need there. Unless we want to give users the same option.)

We could also make it configurable at the library level, though I don't love global configs like that.

(We can't tie the configuration to the top-level graph, because constructor calls are made _before_ the objects are added to the graph. So that won't work unless we wanted to redesign the API so that nodes and edges are constructed using methods of their parent graph, e.g.):

```python
g = pydot.Graph()
g.new_node(<constructor args>)
# implicitly executes:
# n = pydot.Node(<constructor args>, g.config_options)
# g.add_node(n)
```
